replicaCount: 1

image:
  repository: vector-db-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

cohereApiKey: ""  # not committed; override via `--set` in dev
secretName: vector-db-api-secret