apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vector-db-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vector-db-api
  template:
    metadata:
      labels:
        app: vector-db-api
    spec:
      containers:
        - name: vector-db-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources: {{ toYaml .Values.resources | nindent 12 }}
