# helmchart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vector-db-api.fullname" . }}-secret
type: Opaque
stringData:
  COHERE_API_KEY: {{ .Values.cohereApiKey | quote }}
