apiVersion: v1
kind: Service
metadata:
  name: {{ include "vector-db-api.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
